---
# install and setup NRPE and checks

- name: Check Operating System
  fail:
    msg="You're not running a supported operating system (CentOS, RHEL 7+, Rocky, Fedora or FreeBSD)"
  when:
    - ansible_os_family != "RedHat"
    - ansible_os_family != "Rocky"
    - ansible_distribution_major_version|int < 7
    - ansible_os_family != "FreeBSD

- name: Import EPEL7 GPG Key
  rpm_key: key=https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
    state=present
  become: true
  when: ansible_distribution_major_version|int == 7 and ansible_os_family == "RedHat"

- name: Import EPEL8 GPG Key
  rpm_key: key=https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8
    state=present
  become: true
  when:
    - ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 8

- name: Import EPEL9 GPG Key
  rpm_key: key=https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9
    state=present
  become: true
  when:
    - ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 9

- name: Check for EPEL7 repo
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state=present
  become: true
  when: ansible_distribution_major_version|int == 7 and ansible_os_family == "RedHat"

- name: Check for EPEL8 repo
  dnf: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    state=present
  become: true
  when:
    - ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 8

- name: Check for EPEL9 repo
  dnf: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm
    state=present
  become: true
  when:
    - ansible_os_family == "RedHat" and ansible_distribution_major_version|int == 9

- name: Install Python3 for Fedora/EL8 and higher minimal clients
  dnf:
    name: ['python3']
    state: present
  become: true
  when: ansible_distribution_major_version|int >= 8 and ansible_system == "Linux"

- name: Symlink Python to Python3 for EL8/Fedora
  file:
    src: /usr/bin/python3
    dest: /usr/bin/python
    state: link
  when: ansible_distribution_major_version|int >= 8 and ansible_python_version|int < 3.6 and ansible_system == "Linux"
  ignore_errors: true

- name: Install NRPE and Common Plugins
  yum:
    name: ['nrpe', 'nagios-plugins-load', 'nagios-plugins-uptime', 'nagios-plugins-swap', 'nagios-plugins-procs',
           'nagios-plugins-users', 'nagios-plugins-disk', 'nagios-plugins-tcp']
    state: present
  become: true
  when: ansible_distribution_major_version|int <= 7 and ansible_os_family == "RedHat"

- name: Install NRPE and Common Plugins for Fedora/EL8/EL9
  dnf:
    name: ['nrpe', 'nagios-plugins-load', 'nagios-plugins-uptime', 'nagios-plugins-swap', 'nagios-plugins-procs',
           'nagios-plugins-users', 'nagios-plugins-disk', 'nagios-plugins-tcp']
    state: present
  become: true
  when: ansible_distribution_major_version|int >= 8 and ansible_system == "Linux"

- name: Check if BSD ports structure exists
  stat:
    path: /usr/ports/net-mgmt/nagios-plugins/distinfo
  when: ansible_system == "FreeBSD"
  register: bsd_ports_structure
  ignore_errors: true

- name: Fetch new BSD ports tree, this might take a while.
  command: portsnap auto
  become: true
  when: ansible_system == "FreeBSD" and bsd_ports_structure.stat.exists

- name: Install NRPE and Common Plugins for FreeBSD, this might take a while.
  pkgng:
    name: ['nrpe3', 'nagios-plugins']
  become: true
  when: ansible_system == "FreeBSD"

- name: Install libsemanage-python
  yum:
    name: ['libsemanage-python']
    state: present
  become: true
  when: ansible_distribution_major_version|int <= 7 and ansible_os_family == "RedHat"
  ignore_errors: true

- name: Set Fact for Root Disk
  ansible.builtin.set_fact:
    host_root_disk: "{{ ansible_mounts|json_query(query)|first }}"
  vars:
    query: "[?mount=='/'].device "

- name: Setup NRPE client configuration
  template:
    src=nrpe.cfg.j2
    dest=/etc/nagios/nrpe.cfg
    force=yes
  become: true
  when: ansible_system == "Linux"

- name: Setup NRPE client configuration on FreeBSD
  template:
    src=nrpe.cfg.j2
    dest=/usr/local/etc/nrpe.cfg
    force=yes
  become: true
  when: ansible_system == "FreeBSD"

- name: Copy mdadm check_raid plugin
  copy:
    src=check_raid
    dest=/usr/lib64/nagios/plugins/check_raid
    mode="a+x"
  become: true
  when: ansible_system == "Linux"

- name: Copy uptime check tool for FreeBSD
  copy:
    src=bsd_check_uptime.sh
    dest=/usr/local/libexec/nagios/bsd_check_uptime
    mode="a+x"
  become: true
  when: ansible_system == "FreeBSD"

# SELinux boolean for nagios
- name: Apply SELinux boolean nagios_run_sudo
  seboolean: name=nagios_run_sudo state=yes persistent=yes
  ignore_errors: true
  when: ansible_distribution_major_version|int <= 7
  become: true

# SELinux boolean for nagios
- name: Apply SELinux boolean logging_syslogd_run_nagios_plugins
  seboolean: name=logging_syslogd_run_nagios_plugins state=yes persistent=yes
  ignore_errors: true
  when: ansible_distribution_major_version|int <= 7
  become: true

- name: Start NRPE service
  command: systemctl restart nrpe.service
  ignore_errors: true
  when: ansible_distribution_major_version|int >= 7 and ansible_system == "Linux"
  become: true

- name: Enable NRPE service on FreeBSD
  lineinfile:
    path: /etc/rc.conf
    line: nrpe3_enable="YES"
    state: present
    backup: true
  when: ansible_system == "FreeBSD"

- name: Start NRPE service on FreeBSD
  service:
    name: nrpe3
    enabled: true
    state: restarted
  when: ansible_system == "FreeBSD"

- name: Set NRPE to start on boot
  command: systemctl enable nrpe.service
  ignore_errors: true
  when: ansible_distribution_major_version|int >= 7 and ansible_os_family == "RedHat"
  become: true

- name: Start NRPE service (EL6)
  command: service nrpe restart
  ignore_errors: true
  when: ansible_distribution_major_version|int <= 6
  become: true

- name: Set NRPE to start on boot (EL6)
  command: chkconfig nrpe on
  ignore_errors: true
  when: ansible_distribution_major_version|int <= 6
  become: true
